[features]
seeds = true
skip-lint = false
resolution = true

[programs.localnet]
nftx = "Fb4qrJcT6BzESLcqHk8NPKTdVYddri6DaMr8kN1qPvhz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
